import type { UiLayout } from '~/lib/uiTypes';

export interface BuilderPreset {
  id: string;
  name: string;
  description: string;
  icon: string;
  layout: UiLayout;
}

export const BUILDER_PRESETS: BuilderPreset[] = [
  {
    id: 'pos-screen',
    name: 'POS Screen',
    description: 'Point-of-sale layout with a product table and action buttons.',
    icon: 'monitor',
    layout: {
      version: 2,
      resolution: { width: 1280, height: 720 },
      modals: [],
      elements: [
        {
          id: 'pos-title',
          type: 'text',
          label: 'title',
          position: { x: 40, y: 32, width: 400, height: 40, zIndex: 1 },
          content: 'Point of Sale',
          fontSize: 28,
          fontWeight: 'bold',
          color: '#ffffff',
          align: 'left',
        },
        {
          id: 'pos-table',
          type: 'table-view',
          label: 'products',
          position: { x: 40, y: 96, width: 800, height: 480, zIndex: 1 },
          tableName: '',
          columns: [],
        },
        {
          id: 'pos-checkout',
          type: 'button',
          label: 'checkout',
          position: { x: 872, y: 96, width: 180, height: 48, zIndex: 2 },
          text: 'Checkout',
          variant: 'primary',
        },
        {
          id: 'pos-cancel',
          type: 'button',
          label: 'cancel',
          position: { x: 872, y: 160, width: 180, height: 48, zIndex: 2 },
          text: 'Cancel',
          variant: 'secondary',
        },
        {
          id: 'pos-qty',
          type: 'input-field',
          label: 'quantity',
          position: { x: 872, y: 232, width: 180, height: 44, zIndex: 2 },
          fieldName: 'quantity',
          placeholder: 'Qty',
          inputType: 'number',
        },
      ],
    },
  },
  {
    id: 'inventory-list',
    name: 'Inventory List',
    description: 'Full-width inventory table with add and filter controls.',
    icon: 'list',
    layout: {
      version: 2,
      resolution: { width: 1280, height: 720 },
      modals: [],
      elements: [
        {
          id: 'inv-title',
          type: 'text',
          label: 'title',
          position: { x: 40, y: 32, width: 500, height: 36, zIndex: 1 },
          content: 'Inventory',
          fontSize: 24,
          fontWeight: 'semibold',
          color: '#ffffff',
          align: 'left',
        },
        {
          id: 'inv-search',
          type: 'input-field',
          label: 'search',
          position: { x: 40, y: 88, width: 300, height: 44, zIndex: 2 },
          fieldName: 'search',
          placeholder: 'Search items…',
          inputType: 'text',
        },
        {
          id: 'inv-add',
          type: 'button',
          label: 'add',
          position: { x: 1096, y: 88, width: 144, height: 44, zIndex: 2 },
          text: 'Add Item',
          variant: 'primary',
        },
        {
          id: 'inv-table',
          type: 'table-view',
          label: 'inventory',
          position: { x: 40, y: 152, width: 1200, height: 520, zIndex: 1 },
          tableName: '',
          columns: [],
        },
      ],
    },
  },
  {
    id: 'login-screen',
    name: 'Login Screen',
    description: 'Simple centered login form with username and password fields.',
    icon: 'lock',
    layout: {
      version: 2,
      resolution: { width: 1280, height: 720 },
      modals: [],
      elements: [
        {
          id: 'login-title',
          type: 'text',
          label: 'title',
          position: { x: 490, y: 200, width: 300, height: 48, zIndex: 1 },
          content: 'Welcome back',
          fontSize: 30,
          fontWeight: 'bold',
          color: '#ffffff',
          align: 'center',
        },
        {
          id: 'login-sub',
          type: 'text',
          label: 'subtitle',
          position: { x: 490, y: 252, width: 300, height: 28, zIndex: 1 },
          content: 'Sign in to your account',
          fontSize: 14,
          fontWeight: 'normal',
          color: 'rgba(255,255,255,0.5)',
          align: 'center',
        },
        {
          id: 'login-user',
          type: 'input-field',
          label: 'username',
          position: { x: 490, y: 310, width: 300, height: 48, zIndex: 2 },
          fieldName: 'username',
          placeholder: 'Username',
          inputType: 'text',
        },
        {
          id: 'login-pass',
          type: 'input-field',
          label: 'password',
          position: { x: 490, y: 370, width: 300, height: 48, zIndex: 2 },
          fieldName: 'password',
          placeholder: 'Password',
          inputType: 'text',
        },
        {
          id: 'login-btn',
          type: 'button',
          label: 'login',
          position: { x: 490, y: 436, width: 300, height: 52, zIndex: 2 },
          text: 'Sign In',
          variant: 'primary',
        },
      ],
    },
  },
  {
    id: 'dashboard-charts',
    name: 'Dashboard',
    description: 'Analytics dashboard with KPI text and chart widgets.',
    icon: 'chart',
    layout: {
      version: 2,
      resolution: { width: 1280, height: 720 },
      modals: [],
      elements: [
        {
          id: 'dash-title',
          type: 'text',
          label: 'title',
          position: { x: 40, y: 32, width: 400, height: 36, zIndex: 1 },
          content: 'Dashboard',
          fontSize: 24,
          fontWeight: 'bold',
          color: '#ffffff',
          align: 'left',
        },
        {
          id: 'dash-chart1',
          type: 'chart',
          label: 'bar chart',
          position: { x: 40, y: 88, width: 580, height: 280, zIndex: 1 },
          chartType: 'bar',
          tableName: '',
          labelColumn: '',
          valueColumn: '',
        },
        {
          id: 'dash-chart2',
          type: 'chart',
          label: 'pie chart',
          position: { x: 660, y: 88, width: 580, height: 280, zIndex: 1 },
          chartType: 'pie',
          tableName: '',
          labelColumn: '',
          valueColumn: '',
        },
        {
          id: 'dash-chart3',
          type: 'chart',
          label: 'line chart',
          position: { x: 40, y: 400, width: 1200, height: 280, zIndex: 1 },
          chartType: 'line',
          tableName: '',
          labelColumn: '',
          valueColumn: '',
        },
      ],
    },
  },
];
