import type { UiLayout } from '~/lib/uiTypes';

export interface BuilderPreset {
  id: string;
  name: string;
  description: string;
  icon: string;
  layout: UiLayout;
}

export const BUILDER_PRESETS: BuilderPreset[] = [
  {
    id: 'cashier-station',
    name: 'Cashier Station',
    description: 'Registrar-style selling screen with a sale panel and open orders queue.',
    icon: 'monitor',
    layout: {
      version: 2,
      resolution: { width: 1280, height: 720 },
      modals: [],
      elements: [
        {
          id: 'cashier-title',
          type: 'text',
          label: 'title',
          position: { x: 40, y: 28, width: 420, height: 44, zIndex: 1 },
          content: 'Front Counter',
          fontSize: 30,
          fontWeight: 'bold',
          color: '#ffffff',
          align: 'left',
        },
        {
          id: 'cashier-subtitle',
          type: 'text',
          label: 'subtitle',
          position: { x: 40, y: 66, width: 560, height: 26, zIndex: 1 },
          content: 'Ring up orders quickly while keeping the queue visible.',
          fontSize: 14,
          fontWeight: 'normal',
          color: 'rgba(255,255,255,0.6)',
          align: 'left',
        },
        {
          id: 'cashier-sale-panel',
          type: 'cart-widget',
          label: 'sale panel',
          position: { x: 40, y: 108, width: 760, height: 500, zIndex: 2 },
          title: 'Cashier Register',
          subtitle: 'Tap products, assign a table number, and submit the current order.',
          productTable: 'products',
          displayColumns: ['name', 'category'],
          priceColumn: 'price',
          orderTable: 'orders',
          submitLabel: 'Submit Order',
          emptyLabel: 'No products are ready for sale yet. Add them from a Catalog Registrar or Inventory terminal first.',
          backgroundColor: '#161116',
          panelColor: 'rgba(255,255,255,0.04)',
          textColor: '#f5ede4',
          accentColor: '#e8748a',
          borderColor: 'rgba(255,255,255,0.08)',
          radius: 26,
        },
        {
          id: 'cashier-open-orders',
          type: 'table-view',
          label: 'open orders',
          position: { x: 824, y: 108, width: 416, height: 500, zIndex: 2 },
          source: 'business-table',
          title: 'Open Orders',
          subtitle: 'What the station still needs to finish.',
          tableName: 'orders',
          columns: ['id', 'table_number', 'total', 'status'],
          pageSize: 12,
          striped: true,
          backgroundColor: '#161116',
          headerBackgroundColor: 'rgba(255,255,255,0.06)',
          textColor: '#f5ede4',
        },
      ],
    },
  },
  {
    id: 'catalog-station',
    name: 'Catalog Registrar',
    description: 'Dedicated product-entry screen for creating sellable items and checking the live catalog before they reach the cashier.',
    icon: 'database',
    layout: {
      version: 2,
      resolution: { width: 1280, height: 720 },
      modals: [],
      elements: [
        {
          id: 'catalog-title',
          type: 'text',
          label: 'title',
          position: { x: 40, y: 28, width: 520, height: 44, zIndex: 1 },
          content: 'Catalog Registrar',
          fontSize: 30,
          fontWeight: 'bold',
          color: '#ffffff',
          align: 'left',
        },
        {
          id: 'catalog-subtitle',
          type: 'text',
          label: 'subtitle',
          position: { x: 40, y: 66, width: 620, height: 26, zIndex: 1 },
          content: 'Create products here, then the cashier register can sell them immediately.',
          fontSize: 14,
          fontWeight: 'normal',
          color: 'rgba(255,255,255,0.6)',
          align: 'left',
        },
        {
          id: 'catalog-product-name',
          type: 'input-field',
          label: 'product name',
          position: { x: 40, y: 116, width: 220, height: 56, zIndex: 2 },
          fieldName: 'name',
          placeholder: 'Product name',
          inputType: 'text',
          backgroundColor: 'rgba(255,255,255,0.06)',
          textColor: '#f5ede4',
          borderColor: 'rgba(255,255,255,0.12)',
          radius: 16,
        },
        {
          id: 'catalog-product-description',
          type: 'input-field',
          label: 'product description',
          position: { x: 276, y: 116, width: 220, height: 56, zIndex: 2 },
          fieldName: 'description',
          placeholder: 'Short description',
          inputType: 'text',
          backgroundColor: 'rgba(255,255,255,0.06)',
          textColor: '#f5ede4',
          borderColor: 'rgba(255,255,255,0.12)',
          radius: 16,
        },
        {
          id: 'catalog-product-category',
          type: 'input-field',
          label: 'product category',
          position: { x: 40, y: 188, width: 220, height: 56, zIndex: 2 },
          fieldName: 'category',
          placeholder: 'Category',
          inputType: 'select',
          options: ['Food', 'Beverage', 'Service', 'Supplies'],
          backgroundColor: 'rgba(255,255,255,0.06)',
          textColor: '#f5ede4',
          borderColor: 'rgba(255,255,255,0.12)',
          radius: 16,
        },
        {
          id: 'catalog-product-price',
          type: 'input-field',
          label: 'product price',
          position: { x: 276, y: 188, width: 220, height: 56, zIndex: 2 },
          fieldName: 'price',
          placeholder: 'Price',
          inputType: 'number',
          backgroundColor: 'rgba(255,255,255,0.06)',
          textColor: '#f5ede4',
          borderColor: 'rgba(255,255,255,0.12)',
          radius: 16,
        },
        {
          id: 'catalog-product-submit',
          type: 'button',
          label: 'add product',
          position: { x: 40, y: 268, width: 456, height: 58, zIndex: 2 },
          text: 'Add Product',
          variant: 'primary',
          backgroundColor: '#e8748a',
          textColor: '#ffffff',
          radius: 18,
          events: [
            {
              trigger: 'click',
              action: {
                type: 'insert',
                table: 'products',
                payload: {
                  name: '$$input.catalog-product-name',
                  description: '$$input.catalog-product-description',
                  category: '$$input.catalog-product-category',
                  price: '$$input.catalog-product-price',
                },
              },
            },
          ],
        },
        {
          id: 'catalog-products-table',
          type: 'table-view',
          label: 'product catalog',
          position: { x: 536, y: 116, width: 704, height: 520, zIndex: 2 },
          source: 'business-table',
          title: 'Product Catalog',
          subtitle: 'Items available for cashier and other staff terminals.',
          tableName: 'products',
          columns: ['name', 'category', 'description', 'price', 'available'],
          pageSize: 12,
          striped: true,
          emptyLabel: 'No products have been added yet.',
          backgroundColor: '#161116',
          headerBackgroundColor: 'rgba(255,255,255,0.06)',
          textColor: '#f5ede4',
        },
        {
          id: 'catalog-lookup-title',
          type: 'text',
          label: 'lookup title',
          position: { x: 40, y: 360, width: 320, height: 30, zIndex: 2 },
          content: 'Quick Lookup',
          fontSize: 18,
          fontWeight: 'semibold',
          color: '#ffffff',
          align: 'left',
        },
        {
          id: 'catalog-lookup-name',
          type: 'input-field',
          label: 'lookup name',
          position: { x: 40, y: 400, width: 220, height: 52, zIndex: 2 },
          fieldName: 'lookup_name',
          placeholder: 'Exact product name',
          inputType: 'text',
          backgroundColor: 'rgba(255,255,255,0.06)',
          textColor: '#f5ede4',
          borderColor: 'rgba(255,255,255,0.12)',
          radius: 16,
        },
        {
          id: 'catalog-lookup-button',
          type: 'button',
          label: 'lookup button',
          position: { x: 276, y: 400, width: 220, height: 52, zIndex: 2 },
          text: 'Search Catalog',
          variant: 'secondary',
          backgroundColor: 'rgba(255,255,255,0.10)',
          textColor: '#f5ede4',
          radius: 16,
          events: [
            {
              trigger: 'click',
              action: {
                type: 'query',
                source: 'business-table',
                table: 'products',
                columns: ['name', 'category', 'description', 'price', 'available'],
                where: {
                  name: '$$input.catalog-lookup-name',
                },
                targetElementId: 'catalog-products-table',
                limit: 10,
              },
            },
          ],
        },
      ],
    },
  },
  {
    id: 'inventory-station',
    name: 'Inventory Station',
    description: 'Operations view for stock counts, updates, and restock visibility.',
    icon: 'list',
    layout: {
      version: 2,
      resolution: { width: 1280, height: 720 },
      modals: [],
      elements: [
        {
          id: 'inventory-title',
          type: 'text',
          label: 'title',
          position: { x: 40, y: 28, width: 520, height: 44, zIndex: 1 },
          content: 'Inventory Control',
          fontSize: 30,
          fontWeight: 'bold',
          color: '#ffffff',
          align: 'left',
        },
        {
          id: 'inventory-table',
          type: 'table-view',
          label: 'inventory overview',
          position: { x: 40, y: 96, width: 760, height: 540, zIndex: 2 },
          source: 'business-table',
          title: 'Inventory Overview',
          subtitle: 'Monitor quantity, units, and reorder thresholds.',
          tableName: 'inventory',
          columns: ['item_name', 'quantity', 'unit', 'reorder_at'],
          pageSize: 12,
          striped: true,
          backgroundColor: '#161116',
          headerBackgroundColor: 'rgba(255,255,255,0.06)',
          textColor: '#f5ede4',
        },
        {
          id: 'inventory-chart',
          type: 'chart',
          label: 'stock chart',
          position: { x: 824, y: 96, width: 416, height: 260, zIndex: 2 },
          source: 'business-table',
          title: 'Stock Levels',
          subtitle: 'Fast visual comparison of available stock.',
          chartType: 'bar',
          aggregation: 'sum',
          tableName: 'inventory',
          labelColumn: 'item_name',
          valueColumn: 'quantity',
          backgroundColor: '#161116',
          textColor: '#f5ede4',
          colorPalette: ['#e8748a', '#10b981', '#0ea5e9'],
        },
        {
          id: 'inventory-upload',
          type: 'upload',
          label: 'inventory upload',
          position: { x: 824, y: 380, width: 416, height: 120, zIndex: 2 },
          bucket: 'products',
          buttonLabel: 'Upload Stock Sheet',
          pathTemplate: 'inventory/{{date}}.csv',
          accept: ['.csv', '.xlsx'],
          backgroundColor: 'rgba(255,255,255,0.05)',
          textColor: '#f5ede4',
          borderColor: 'rgba(255,255,255,0.18)',
          radius: 20,
        },
      ],
    },
  },
  {
    id: 'kitchen-station',
    name: 'Kitchen Display',
    description: 'Back-of-house order board that refreshes automatically as the cashier sends new tickets.',
    icon: 'monitor',
    layout: {
      version: 2,
      resolution: { width: 1280, height: 720 },
      modals: [],
      elements: [
        {
          id: 'kitchen-title',
          type: 'text',
          label: 'title',
          position: { x: 40, y: 28, width: 520, height: 44, zIndex: 1 },
          content: 'Kitchen Queue',
          fontSize: 30,
          fontWeight: 'bold',
          color: '#ffffff',
          align: 'left',
        },
        {
          id: 'kitchen-subtitle',
          type: 'text',
          label: 'subtitle',
          position: { x: 40, y: 66, width: 760, height: 26, zIndex: 1 },
          content: 'New cashier orders appear here automatically so the back-of-house can start preparation right away.',
          fontSize: 14,
          fontWeight: 'normal',
          color: 'rgba(255,255,255,0.6)',
          align: 'left',
        },
        {
          id: 'kitchen-orders-board',
          type: 'table-view',
          label: 'kitchen orders',
          position: { x: 40, y: 108, width: 1200, height: 560, zIndex: 2 },
          source: 'business-table',
          title: 'Incoming Orders',
          subtitle: 'Auto-refreshes every few seconds while the station is open.',
          tableName: 'orders',
          columns: ['created_at', 'table_number', 'items', 'status', 'total'],
          pageSize: 20,
          autoRefreshMs: 3000,
          orderBy: 'created_at',
          descending: true,
          striped: true,
          emptyLabel: 'No orders have reached the kitchen yet.',
          backgroundColor: '#161116',
          headerBackgroundColor: 'rgba(255,255,255,0.06)',
          textColor: '#f5ede4',
        },
      ],
    },
  },
  {
    id: 'reports-station',
    name: 'Reports Station',
    description: 'Read-only reporting screen with audit feed and activity charts.',
    icon: 'chart',
    layout: {
      version: 2,
      resolution: { width: 1280, height: 720 },
      modals: [],
      elements: [
        {
          id: 'reports-title',
          type: 'text',
          label: 'title',
          position: { x: 40, y: 28, width: 420, height: 44, zIndex: 1 },
          content: 'Operations Reports',
          fontSize: 30,
          fontWeight: 'bold',
          color: '#ffffff',
          align: 'left',
        },
        {
          id: 'reports-chart',
          type: 'chart',
          label: 'action breakdown',
          position: { x: 40, y: 96, width: 520, height: 280, zIndex: 2 },
          source: 'audit-log',
          title: 'Action Breakdown',
          subtitle: 'Count actions by type across the audit trail.',
          chartType: 'bar',
          aggregation: 'count',
          labelColumn: 'action_type',
          backgroundColor: '#161116',
          textColor: '#f5ede4',
          colorPalette: ['#e8748a', '#0ea5e9', '#10b981'],
        },
        {
          id: 'reports-table',
          type: 'table-view',
          label: 'activity feed',
          position: { x: 584, y: 96, width: 656, height: 540, zIndex: 2 },
          source: 'audit-log',
          title: 'Activity Feed',
          subtitle: 'Review who changed what and when.',
          columns: ['created_at', 'actor_name', 'action_type', 'target_table'],
          pageSize: 16,
          striped: true,
          backgroundColor: '#161116',
          headerBackgroundColor: 'rgba(255,255,255,0.06)',
          textColor: '#f5ede4',
        },
        {
          id: 'reports-trend',
          type: 'chart',
          label: 'target table trend',
          position: { x: 40, y: 396, width: 520, height: 240, zIndex: 2 },
          source: 'audit-log',
          title: 'Target Table Trend',
          subtitle: 'Which tables are receiving the most activity.',
          chartType: 'pie',
          aggregation: 'count',
          labelColumn: 'target_table',
          backgroundColor: '#161116',
          textColor: '#f5ede4',
          colorPalette: ['#f59e0b', '#e8748a', '#0ea5e9', '#10b981'],
        },
      ],
    },
  },
  {
    id: 'pos-screen',
    name: 'POS Screen',
    description: 'Point-of-sale layout with a product table and action buttons.',
    icon: 'monitor',
    layout: {
      version: 2,
      resolution: { width: 1280, height: 720 },
      modals: [],
      elements: [
        {
          id: 'pos-title',
          type: 'text',
          label: 'title',
          position: { x: 40, y: 32, width: 400, height: 40, zIndex: 1 },
          content: 'Point of Sale',
          fontSize: 28,
          fontWeight: 'bold',
          color: '#ffffff',
          align: 'left',
        },
        {
          id: 'pos-table',
          type: 'table-view',
          label: 'products',
          position: { x: 40, y: 96, width: 800, height: 480, zIndex: 1 },
          tableName: '',
          columns: [],
        },
        {
          id: 'pos-checkout',
          type: 'button',
          label: 'checkout',
          position: { x: 872, y: 96, width: 180, height: 48, zIndex: 2 },
          text: 'Checkout',
          variant: 'primary',
        },
        {
          id: 'pos-cancel',
          type: 'button',
          label: 'cancel',
          position: { x: 872, y: 160, width: 180, height: 48, zIndex: 2 },
          text: 'Cancel',
          variant: 'secondary',
        },
        {
          id: 'pos-qty',
          type: 'input-field',
          label: 'quantity',
          position: { x: 872, y: 232, width: 180, height: 44, zIndex: 2 },
          fieldName: 'quantity',
          placeholder: 'Qty',
          inputType: 'number',
        },
      ],
    },
  },
  {
    id: 'inventory-list',
    name: 'Inventory List',
    description: 'Full-width inventory table with add and filter controls.',
    icon: 'list',
    layout: {
      version: 2,
      resolution: { width: 1280, height: 720 },
      modals: [],
      elements: [
        {
          id: 'inv-title',
          type: 'text',
          label: 'title',
          position: { x: 40, y: 32, width: 500, height: 36, zIndex: 1 },
          content: 'Inventory',
          fontSize: 24,
          fontWeight: 'semibold',
          color: '#ffffff',
          align: 'left',
        },
        {
          id: 'inv-search',
          type: 'input-field',
          label: 'search',
          position: { x: 40, y: 88, width: 300, height: 44, zIndex: 2 },
          fieldName: 'search',
          placeholder: 'Search items…',
          inputType: 'text',
        },
        {
          id: 'inv-add',
          type: 'button',
          label: 'add',
          position: { x: 1096, y: 88, width: 144, height: 44, zIndex: 2 },
          text: 'Add Item',
          variant: 'primary',
        },
        {
          id: 'inv-table',
          type: 'table-view',
          label: 'inventory',
          position: { x: 40, y: 152, width: 1200, height: 520, zIndex: 1 },
          tableName: '',
          columns: [],
        },
      ],
    },
  },
  {
    id: 'login-screen',
    name: 'Login Screen',
    description: 'Simple centered login form with username and password fields.',
    icon: 'lock',
    layout: {
      version: 2,
      resolution: { width: 1280, height: 720 },
      modals: [],
      elements: [
        {
          id: 'login-title',
          type: 'text',
          label: 'title',
          position: { x: 490, y: 200, width: 300, height: 48, zIndex: 1 },
          content: 'Welcome back',
          fontSize: 30,
          fontWeight: 'bold',
          color: '#ffffff',
          align: 'center',
        },
        {
          id: 'login-sub',
          type: 'text',
          label: 'subtitle',
          position: { x: 490, y: 252, width: 300, height: 28, zIndex: 1 },
          content: 'Sign in to your account',
          fontSize: 14,
          fontWeight: 'normal',
          color: 'rgba(255,255,255,0.5)',
          align: 'center',
        },
        {
          id: 'login-user',
          type: 'input-field',
          label: 'username',
          position: { x: 490, y: 310, width: 300, height: 48, zIndex: 2 },
          fieldName: 'username',
          placeholder: 'Username',
          inputType: 'text',
        },
        {
          id: 'login-pass',
          type: 'input-field',
          label: 'password',
          position: { x: 490, y: 370, width: 300, height: 48, zIndex: 2 },
          fieldName: 'password',
          placeholder: 'Password',
          inputType: 'text',
        },
        {
          id: 'login-btn',
          type: 'button',
          label: 'login',
          position: { x: 490, y: 436, width: 300, height: 52, zIndex: 2 },
          text: 'Sign In',
          variant: 'primary',
        },
      ],
    },
  },
  {
    id: 'dashboard-charts',
    name: 'Dashboard',
    description: 'Analytics dashboard with KPI text and chart widgets.',
    icon: 'chart',
    layout: {
      version: 2,
      resolution: { width: 1280, height: 720 },
      modals: [],
      elements: [
        {
          id: 'dash-title',
          type: 'text',
          label: 'title',
          position: { x: 40, y: 32, width: 400, height: 36, zIndex: 1 },
          content: 'Dashboard',
          fontSize: 24,
          fontWeight: 'bold',
          color: '#ffffff',
          align: 'left',
        },
        {
          id: 'dash-chart1',
          type: 'chart',
          label: 'bar chart',
          position: { x: 40, y: 88, width: 580, height: 280, zIndex: 1 },
          chartType: 'bar',
          tableName: '',
          labelColumn: '',
          valueColumn: '',
        },
        {
          id: 'dash-chart2',
          type: 'chart',
          label: 'pie chart',
          position: { x: 660, y: 88, width: 580, height: 280, zIndex: 1 },
          chartType: 'pie',
          tableName: '',
          labelColumn: '',
          valueColumn: '',
        },
        {
          id: 'dash-chart3',
          type: 'chart',
          label: 'line chart',
          position: { x: 40, y: 400, width: 1200, height: 280, zIndex: 1 },
          chartType: 'line',
          tableName: '',
          labelColumn: '',
          valueColumn: '',
        },
      ],
    },
  },
];
